### ISSUE TITLE
Add static factory method for "new JacksonMapper.Builder()"

### ISSUE THREAD

**Issue by btiernay** [bguerout/jongo#127]
Having a static method `JacksonMapper.Builder.jacksonMapper` or similar would aid in the construction of nicer internal DSLs as described here:

http://stackoverflow.com/questions/9942155/custom-java-query-class-dsl-builder-pattern-static-imports-or-something-else

Thus, this would be possible: 
```
import static JacksonMapper.Builder.jacksonMapper;
...
Jongo jongo = new Jongo(db, jacksonMapper()
      .registerModule(new JodaModule())
      .enable(MapperFeature.AUTO_DETECT_GETTERS)
      .withView(Views.Public.class)
      .build()
);
```

which, imo, is more terse and readable, while carrying the same semantic meaning.

**Comment by bguerout** [comment]
Better latte than never :-)
