### ISSUE TITLE
find().projection("_id:1").as(ObjectId.class) returns incorrect ObjectId's

### ISSUE THREAD

**Issue by nilswx** [bguerout/jongo#170]
Hey everyone, thanks for Jongo! We are currently using it for accessing the MongoDB of our game server and it's been a real pleasure to work with.

However, I think I might have encountered a bug! I'm trying to query a list of ObjectId fields from a collection. Just the ID's, nothing else. Simplified example below.

``` java
for(ObjectId userId : userCollection.find().projection("{_id:1}").as(ObjectId.class))
{
   // Do something with userId
}
```

Expected result: the ObjectId's of all the documents in the userCollection.

But in Jongo 0.4, this returns incorrect ObjectId's... ObjectId's that don't even look like the ID's from the collection.

What's up? Is this a bug with the deserializer, or is this expected behaviour? How would I tackle this situation?

Thanks! :+1:

**Comment by fedotxxl** [comment]
Is it implemented?
