### ISSUE TITLE
Add QueryBuilder support

### ISSUE THREAD

**Issue by fedotxxl** [bguerout/jongo#173]
I really like Jongo API - it's very good for strict requests to mongo. But request to DB may not be fixed at compile time - it may depends on runtime properties. 

Pls add QueryBuilder similar to `com.mongodb.QueryBuilder`. You can find more description of the problem here - https://groups.google.com/forum/#!topic/jongo-user/whTqqPVVvmM

I've temporary solved this problem in a very dirty way:
1. Added support for DBObject to `MongoCollection.find` method
2. Constructed DBObject using `com.mongodb.QueryBuilder`
3. Changed `BsonQueryFactory` to be able to marshall constructed DBObject (btw is it ok that `BsonQueryFactory` parses query and marshalls params at the same time? Shouldn't it be two separate classes?)

**Comment by obazoud** [comment]
@bguerout could you provide a snippet ?

**Comment by bguerout** [comment]
Hello, thanks for your feedback.
What about implementing a custom QueryFactory ?

**Comment by obazoud** [comment]
Yes it can be an option, but I should copy/paste 90% of code of BsonQueryFactory.

**Comment by bguerout** [comment]
May be BsonQueryFactory should be refactored to ease extensibility

**Comment by obazoud** [comment]
It will be nice :)

**Comment by stayfocus** [comment]
+1!

**Comment by alim-akbashev** [comment]
+1

**Comment by nikos** [comment]
+1

**Comment by knes1** [comment]
+1
I use Java driver's QueryBuilder for now like this: (note - this is Kotlin code, hence the unusual syntax):

```kotlin
//static imports for QueryBuilder.* methods such as start()
import com.mongodb.QueryBuilder
import com.mongodb.QueryBuilder.*

...

﻿    /**
     * Find persons in time zone specifified by zoneId that have never answered a call and haven't been called since notCallSince
     */
    fun findUnansweredNotCalledSince(notCalledSince: LocalDateTime, zoneId: ZoneId): Iterable<Person> {
        val date = Date.from(ZonedDateTime.of(notCalledSince, zoneId).toInstant())

        val query = QueryBuilder.start().or(
            start("sessionResult").`is`(null).get(),
            start().and(
                start("timeZone").`is`(zoneId.id).get(),
                start("sessionResult.lastInitiated").lessThanEquals(date).get(),
                start("sessionResult.answered").`is`(false).get()
            ).get()
        )
        return collection.find(query.get().toString()).`as`(classToken);
    }
```

**Comment by leandrostoroli** [comment]
+1

**Comment by bguerout** [comment]
Hello,

1.4.0 should include helpers to deal with new mongo java driver API

```java
  Document document = new Document("name", "Abby").append("address", "123 Wall Street");

  collection.insertOne(document);
```
You can find more informations here https://github.com/bguerout/jongo/issues/254 and a working example : https://github.com/bguerout/jongo/blob/master/src/test/java/org/jongo/v3/QueryBuilderTest.java#L29

Does it fit your needs ?

**Comment by yehancha** [comment]
+1

**Comment by Gnaneshwar511** [comment]
+1
