### ISSUE TITLE
Bulk Upsert

### ISSUE THREAD

**Issue by arcadius** [bguerout/jongo#183]
Hello.

I have been looking into the documentation but could not find this feature.

I have about 100k upserts and I would like to avoid server round-trip.
Instead of the following 3 statement, is it possible to build the 3 queries on the client and submit them as one to the server?

``` java
friends.update("{name: 'Joe'}").upsert().multi().with("{$inc: {age: 1}}");
friends.update("{name: 'Joy''}").upsert().multi().with("{$inc: {age: 1}}");
friends.update("{name: 'Jim'}").upsert().multi().with("{$inc: {age: 1}}");
```

I know I will have to iterate to build the queries. That's OK as far as there is only 1 round-trip to the server.

Many thanks.

**Comment by arcadius** [comment]
Any news about this issue?

**Comment by btiernay** [comment]
This would be very useful actually. :+1:

**Comment by nealvs** [comment]
Bulk inserts, bulk updates, bulk upserts are needed in Jongo for write-heavy applications.

**Comment by fhur** [comment]
Any progress on this feature @bguerout, I would be happy to help implementing (or testing) this.

**Comment by cristinak** [comment]
Hi all, I've encountered the same scenario: I need to update k items in the db with the same data and I would really need a bulk update - any progress on this ? Many thanks!

**Comment by bguerout** [comment]
Hello,

Future Jongo 1.4 releases will come with a new native API to be able to deal with mongo java driver 3+.
I'm going to check how to send bulk insert with it.
