### ISSUE TITLE
@Id annotation collides with non-mongodb jackson-based serialization

### ISSUE THREAD

**Issue by reyesr** [bguerout/jongo#212]
This is exactly the same issue than #193 which was unfortunatly closed, but maybe the issue was not well understood (I'm not sure, just a feeling from reading the discussion, sorry if I misinterpreted).

The @org.jongo.marshall.jackson.oid.Id annotation is a roughly an alias to @JsonProperty("_id") to have Jackson rename a pojo property name to "_id" when sending it to mongodb. 

However, this is handled program-wide, and using Jackson to serialize this very same pojo for any other purpose (say, sending it to the browser) still modifies the property name to "_id". I think using a Jongo-specific annotation should not impact other jackson usage in the program.

Example in the real-world: I updated a website to Play 2.2, which now uses Jackson 2, and my pojos are now all wrong when I send them to the browser (object ids are now renamed "_id" instead of their normal name) because Play 2 invokes Jackson 2, and it now takes the @Id annotation into account.

is there a way to avoid this without side-effects? In #193 chrisirhc suggested a specific @MongoId annotation, this sounds like a good idea to me.

**Comment by bguerout** [comment]
You are right lot of people complains about that and this is probably a mistake with have made at the begin.
I'm going to add a look but i'm a bit afraid of how to "ask" people to update their code.

**Comment by bguerout** [comment]
Ok so we can probably mark @Id and @ObjectId as deprecated in the next version and provide a custom AnnotationIntrospector to handle newly created @JongoId and @JongoObjectId

**Comment by bguerout** [comment]
Hi,
POJOs can now be annotated with @MongoId (same as @Id) and @MongoObjectId (same as @ObjectId). 
These new annotations are only visible by the ObjectMapper provided with Jongo.
Your POJOs can be used with another ObjectMapper (eg. the one provided with Jersey) without any side effect.
Note that @Id and @ObjectId are now deprecated nevertheless backward compatibility has been preserved.

**Comment by bguerout** [comment]
You can test these new annotations with our latest early release.
**This version must be considered as a SNAPSHOT of future 1.2 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.2-early-20150210-0143</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```
