### ISSUE TITLE
@Id/@ObjectId now deserialize meta data of key as opposed to String key value

### ISSUE THREAD

**Issue by scalabilitysolved** [bguerout/jongo#221]
Hi, I'm having an issue after having upgraded Jongo and Play framework where a previous String id annotated with both @Id and @ObjectId would produce a value like this once retrieved from Mongo

`{"name":"Owen","id":"53fcbedae4b0123e12632639"}`

but now produces

`{"name":"Owen","_id":{"time":1409072858000,"date":1409072858000,"timestamp":1409072858,"new":false,"timeSecond":1409072858,"inc":308487737,"machine":-458223042}}`

I've written the issue up in more detail on Stackoverflow, if you'd like me to convert the code from there to here I'd be happy to do that.  http://stackoverflow.com/questions/25512381/rename-objectid-id-to-id-in-jackson-deserialization-with-jongo-and-mongodb

Any help and your time is greatly appreciated :)

**Comment by bguerout** [comment]
link https://github.com/bguerout/jongo/issues/212
