### ISSUE TITLE
Jongo Overriding the BasicDBObject to LazyBSONObject

### ISSUE THREAD

**Issue by mukulgupta2507** [bguerout/jongo#228]
Hi,

I'm facing a weird issue while using jongo in my code. I have some legacy code written using BasicDBObject/DBObject. When I added jongo dependencies, it's giving me following exception:

``` java
org.jboss.resteasy.spi.UnhandledException: java.lang.UnsupportedOperationException: Object is read only
    at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76)
    at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)

Caused by: java.lang.UnsupportedOperationException: Object is read only
    at org.bson.LazyBSONObject.put(LazyBSONObject.java:353)
```

My legacy code is something like this:

``` java
Mongo mongo = new MongoClient();
DBCollection coll = mongo.getDB("myDB").getCollection("myCollection");
DBCursor cursor = coll.find(new BasicDBObject("key","value").toString());
DBObject obj = cursor.next();       
obj.put("newkey":"value");          // showing error it seems can't modify the ready only object
```

I have following dependencies:

``` xml
<fasterxml.jackson.core.version>2.3.0</fasterxml.jackson.core.version>
<jongo.version>1.0</jongo.version>
<mongo-java-driver.version>2.12.2</mongo-java-driver.version>
```

Any idea what can be a possible cause. It was working fine before adding jongo dependecies, my guess is jongo is overriding the internal behaviour of BasicDBObject and converting it to read only.

Thanks

**Comment by mox601** [comment]
I hit this issue when trying to use the same MongoClient (and then get a DB used to build a Jongo instance) with spring-data.

**Comment by gclayburg** [comment]
I'm running into a similar issue, @mox601  So is the solution to not initialize Jongo with the MongoClient used by Spring Data?

**Comment by gclayburg** [comment]
FYI - for anyone else stumbling into this issue when trying to use some Jongo based features in a Spring Data MongoDB applicatoin, it is working for me to initialize Jongo with a fresh MongoClient instance instead of reusing the MongoClient in the Spring context.
