### ISSUE TITLE
Jongo update doesn't update all fields in this case.

### ISSUE THREAD

**Issue by netbrain** [bguerout/jongo#231]
Say i have the java classes: 

``` java
Parent {
  ObjectId _id;
}

Child {
 ObjectId _id;
 ObjectId parent;
}
```

A standard parent/child relationship.
If i create a parent, and a child, and set the child to have a reference to parent.

If i then later set the childs parent to null an try to update the collection as follows:

``` java
Child child = collection.findOne("{_id: #}",id).as(Child.class);
child.setParent(null);
collection.update(child.getId()).with(child);
```

The childs parent reference is never set to null. Instead i am forced to run

``` java
collection.update(id).with("{$set: {parent: #}}",null);
```

I'm guessing that if I set the parent field to be a String instead of an ObjectId then this would work fine, as it seems that jongo handles primitives just fine. But shouldn't this case work when using an ObjectId?

**Comment by lucaskatayama** [comment]
What if I want set a field to null????

For instance...

I have

```javascript
{
  'nome' : 'John Doe',
  'phone' : '123'
}
```

And I want 
```javascript
{
  'nome' : 'John Doe',
  'phone' : null
}
```

I need to retrieve entire object, set only one field to null and them update?????

**Comment by bguerout** [comment]
Hello,

You can use $set operator:

```java
collection.findAndModify().with("{$set: {phone: null}}").returnNew().as(Person.class);
//or
collection.update("{}").upsert().with("{$set:{name:null}}");

```
