### ISSUE TITLE
MongoCollection.ensureIndex() does not support multiple curly braces

### ISSUE THREAD

**Issue by fabiomargarido** [bguerout/jongo#234]
The `ensureIndex()` method of the `MongoCollection` class does not support a string with multiple curly braces, such as this example from the docs:

    db.collection.ensureIndex(
        { "$**": "text" },
        { name: "TextIndex" }
    )

Furthermore, such a call does not raise any exceptions, leading the user to believe it's been successfully executed as expected. This can be quite problematic for TTL indexes, such as:

    db.collection.ensureIndex({ "createdAt": 1 }, { expireAfterSeconds: 3600 });

A regular index will be created and the TTL component will be ignored.

**Comment by komusubi** [comment]
you should use MongoCollection#ensureIndex(String, String)

https://github.com/bguerout/jongo/blob/master/src/main/java/org/jongo/MongoCollection.java#L195

it is works for me.
ensureIndex("{createdAt: 1}", "{expireAfterSeconds: 3600}");

**Comment by bguerout** [comment]
Exact you have ti use the ensureIndex with two parameters.
The query seems not to be detected has invalid because the JSON.parse method provided by the driver just ignore data after the comma.

**Comment by fabiomargarido** [comment]
Ugh, don't know how I missed that.

Sorry for the noise.
