### ISSUE TITLE
geoNear operator in aggregate causes 

### ISSUE THREAD

**Issue by sebclaude** [bguerout/jongo#240]
The usage of $geoNear operation produces a JSONParseException.

For example : 
return event.aggregate("{ $geoNear: {near: [3.37343,48.97349], distanceField: 'location', maxDistance: 15/111.32 } }")
.and("{$group: { _id : '$brand', volume: {$sum : 1}} }").as(StatGeo.class);

**Comment by bguerout** [comment]
Hello,

Here is few examples from our tests : https://github.com/bguerout/jongo/blob/443b461e47acdcffb9f51efafb291b7e0c805c26/src/test/java/org/jongo/CommandTest.java#L80
