### ISSUE TITLE
How do I config in Play to connect to multiple MongoDBs?

### ISSUE THREAD

**Issue by joereger** [bguerout/jongo#242]
Howdy -

We'd like to configure Jongo running within Play framework 2.0.6 to talk to multiple MongoDB hosts on a per-collection basis.

BACKGROUND
We are currently using Jongo as the driver for MongoDB.  We're using env vars and conf files to set connection params:
jongo.db.host="foo.localhost"
jongo.db.port="11432"
...

And then we access the database collections with typical:
   public static MongoCollection collection() {
        return JongoDB.getCollection("accounts");
    }

QUESTION
Within the Play 2.0.6 framework, is there a way to configure Jongo to connect to different databases for different collections?  For example, the "accounts" collection is on MongoDB1 and the "foo" collection is on MongoDB2.

Thanks,

Joe

**Comment by bguerout** [comment]
Hello,

You have to create an instance of jongo per db.
Are you using the jongo  play plugin : https://github.com/alexanderjarvis/play-jongo ?

**Comment by joereger** [comment]
Thanks... we are using Jongo and I hadn't seen the jongo play plugin before.  

The problem we have is that we're running Play 2.0.6 and have a few biggish hurdles to get upgraded to at least 2.1.x which is the minimum that play-jongo supports.

Have you seen anybody doing multi-db with 2.0.x and some base Jongo driver?

Thanks for your support!
