### ISSUE TITLE
Unable to pass Object mapper in the Jongo constructor.

### ISSUE THREAD

**Issue by RakeshChouhan** [bguerout/jongo#243]
I am unable to pass the Objectmapper in the Jongo Constructor. 

Here is the code.

ObjectMapper objectMapper = new ObjectMapper();
Builder builder = new JacksonMapper.Builder(objectMapper);
Jongo jongo = new Jongo(db,builder.build());

I am getting error

Exception in thread "main" java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Unknown Source)
    at java.nio.HeapByteBuffer.get(Unknown Source)
    at org.bson.io.BSONByteBuffer.get(BSONByteBuffer.java:51)
    at org.bson.LazyBSONObject.sizeCString(LazyBSONObject.java:640)
    at org.bson.LazyBSONObject.getElement(LazyBSONObject.java:435)
    at org.bson.LazyBSONObject.get(LazyBSONObject.java:415)
    at com.mongodb.LazyWriteableDBObject.get(LazyWriteableDBObject.java:93)
    at org.jongo.Insert$LazyIdDBObject.get(Insert.java:105)
    at com.mongodb.DBCollection.save(DBCollection.java:1040)
    at org.jongo.Insert.save(Insert.java:49)
    at org.jongo.MongoCollection.save(MongoCollection.java:128)

**Comment by bguerout** [comment]
Hello,

Your Mapper have to be able to handle BSON.
You should use JacksonMapper.Builder and configure your mapper with the API
provided by Jongo.

**Comment by RakeshChouhan** [comment]
Hi Benoit,

I have done the same, please look in to the above code.

**Comment by bguerout** [comment]
Oups sorry.
Can you post a code snippet where you call the save method ?

**Comment by RakeshChouhan** [comment]
Hi Benoit, 

This is my TestQuery.java class

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.TimeZone;
import java.util.regex.Pattern;

import org.jongo.MongoCollection;


public class TestQueries {

	public static void main(String[] args) {
		MyObj myObj = new MyObj();
		myObj.setDoa(DateUtil.getDateInString(new Date()));
		myObj.setDob(DateUtil.getDateInString(new Date()));
		myObj.setDoj(DateUtil.getDateInString(new Date()));
		getCollection("testCollection").save(myObj);
		System.out.println("Created object");
		Iterator itr = getCollection("testCollection").find("{doa:{$gt:#}}",getDate()).as(MyObj.class).iterator();
		while(itr.hasNext()){
			
			System.out.println(((MyObj)itr.next()).getDoa());
			
		}
		
	}

	private static Date getDate() {
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
		
		Date result = null;
		try {
			result = simpleDateFormat.parse("01/01/1900");
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return result;
	}

	private static MongoCollection getCollection(String documentName) {
		PlayJongo.openConnection();
		return PlayJongo.getCollection(documentName);
	}

}

PlayJongo is a utility class in which I have written the code to openConnection as per my previous post- 

ObjectMapper objectMapper = new ObjectMapper();
Builder builder = new JacksonMapper.Builder(objectMapper);
Jongo jongo = new Jongo(db,builder.build());
