### ISSUE TITLE
Any example of using Aggregation $group ?

### ISSUE THREAD

**Issue by Alaa-GI** [bguerout/jongo#244]
How can i do this with jongo ? Thank's  
        db.joboffer.aggregate(
             {
             $group : {_id : "$postalCode", total : { $sum : 1 }}
             },
             {
             $sort : {total : -1}
             }
             );

**Comment by bguerout** [comment]
Closed in favor of ML post : https://groups.google.com/forum/?fromgroups#!topic/jongo-user/EwGlBMcfxAM
