### ISSUE TITLE
still active project ?

### ISSUE THREAD

**Issue by mpages** [bguerout/jongo#245]
hi i'm thinking about using jongo for a project but i don't see much activity and looking to 1.1 source, it seems to use deprected mongo driver classes.

**Comment by alex-sherwin** [comment]
also interested to know if jongo will be updated with the latest java driver changes for 3.0

**Comment by dwursteisen** [comment]
Jongo is already updated for Mongo 3.0 driver

see merge https://github.com/bguerout/jongo/commit/aa988ff7746f3ea0740acaa9fda47444e3fd7400

**Comment by yamsellem** [comment]
Yep, but this will be released in 1.2 ;-).

**Comment by bguerout** [comment]
Yes this project is still alive.
1.2 will be released when 3.0.0 driver will be available which is not yet the case (still in beta3).

**Comment by ihr** [comment]
Java Driver 3.0.0 is out! I hope to see my contribution after 2 years of waiting! :-)

**Comment by scalabilitysolved** [comment]
Is there a release date yet for the 1.2 Jongo version? No pressure and thanks for all the great work that goes into it!

**Comment by gurrie** [comment]
+1
