### ISSUE TITLE
maxTimeMS

### ISSUE THREAD

**Issue by twillouer** [bguerout/jongo#247]
Hello,

will there a way to put the maxTimeMS parameter to a cursor ?

http://docs.mongodb.org/manual/reference/method/cursor.maxTimeMS/

Thanks for the great work !

**Comment by bguerout** [comment]
Sorry for the late response :
You can probably use a QueryModifier
```java 
        Iterator<Friend> friends = collection.find()
                .with(new QueryModifier() {
                    public void modify(DBCursor cursor) {
                        cursor.addSpecial("$maxTimeMS", 1);
                    }
                }).as(Friend.class);
```

**Comment by twillouer** [comment]
Thanks ! Didn't see this api !

**Comment by bguerout** [comment]
Here is an example http://jongo.org/#modifiers
But you are right, I'm going to improve the doc

**Comment by twillouer** [comment]
Hum.. didn't work for findOne, right ?

**Comment by twillouer** [comment]
In mongodb 2.13.0 drivers, findOne as the signature 
com.mongodb.DBCollection#findOne(com.mongodb.DBObject, com.mongodb.DBObject, com.mongodb.DBObject, com.mongodb.ReadPreference, long, java.util.concurrent.TimeUnit)

the last two field set the "maxTimeMS" in case of findOne.

I didn't know how to change this in jongo (and if I read correctly the code, there is no way).

Do you know if it will be possible in next version ?

Thanks

**Comment by bguerout** [comment]
Feel free to reopen if needed
