### ISSUE TITLE
LazyWriteableDBObject class dropped from MongoClient

### ISSUE THREAD

**Issue by paulhemmings** [bguerout/jongo#249]
I'm getting the following runtime error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/mongodb/LazyWriteableDBObject
Caused by: java.lang.ClassNotFoundException: com.mongodb.LazyWriteableDBObject

According to the MondoDB page that class was dropped a while back:
https://jira.mongodb.org/secure/ReleaseNote.jspa?projectId=10006&version=10481
"Remove LazyWriteableDBObject and related classes"

Is there a version of Jongo that doesn't use this class? I'm pulling in 1.1

```
compile 'org.mongodb:mongo-java-driver:3.0.0-SNAPSHOT'
compile 'org.jongo:jongo:1.1'
```

**Comment by bguerout** [comment]
Jongo 1.1 is not compatible with new java-driver 3.0+
We are going to release 1.2 soon, in the meanwhile you can use an early version of 1.2
**This version must be considered as a SNAPSHOT of future 1.2 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.2-early-20150210-0143</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```
