### ISSUE TITLE
defference in type of .count() methods

### ISSUE THREAD

**Issue by imysak** [bguerout/jongo#250]
Hi,  MongoCollection::count()  return long type value, however MongoCursor::count() return int type value.
I guess will be better to have consistency there and use long type for all ..count() methods.
// Just to avoid any possible problems there.

**Comment by bguerout** [comment]
Hello,

MongoCursor is just a wrapper around DBCursor which returns an int : 
http://api.mongodb.org/java/2.0/com/mongodb/DBCursor.html#count()

**Comment by imysak** [comment]
I see, thanks for explanation
