### ISSUE TITLE
How to log jongo quries?

### ISSUE THREAD

**Issue by fedotxxl** [bguerout/jongo#256]
Can someone suggest simple way to debug jongo queries?

**Comment by bguerout** [comment]
What about using a RawResultHandler
```java
ResultHandler<DBObject> handler = new RawResultHandler<DBObject>();
Friend john = new Friend("John", "22 Wall Street Avenue");
collection.save(john);

DBObject result = collection.findOne().map(handler);
result.toString()...
```

**Comment by fedotxxl** [comment]
I had problems with aggregation query. In general enabling db profiler - http://docs.mongodb.org/manual/tutorial/manage-the-database-profiler/ - is enough. It would be great to get similar info as app logs (manage it by slf4j)

**Comment by haraldrombaut** [comment]
It would indeed be nice to get logging on what queries are executed.

For example a logging statement on Find.map (LOGGER is and slf4j Logger in this example)

```java
LOGGER.trace("{}: db.{}.find({}, {})", collection.getDB().getName(), collection.getName(), query.toDBObject(), getFieldsAsDBObject());
```

This is possible with aspectj load-time weaving, which I'm trying to avoid using.

**Comment by bguerout** [comment]
You are right.
Here is the issue #27 (created in 2012!) to add logging.
It should be create to add logging capabilities without dependency to logging API
