### ISSUE TITLE
Jongo equivalent not null query

### ISSUE THREAD

**Issue by prithvirajanm** [bguerout/jongo#259]
Hi,
The following query returns result when executed in shell, but returns zero in jongo.
Shell>db.book_store.find({published_date:{$ne:null}});
Jongo> bkstore.find("{published_date:#}","{$ne:null}").as(Book_Store.class);

Can you kindly point out the right way of doing it.
thanks

**Comment by haraldrombaut** [comment]
If you write it like that the query is translated to {published_date:"{$ne:null}"}, so it compares the field to a string. Try bkstore.find("{published_date:{$ne:#}}",null).as(Book_Store.class);

**Comment by bguerout** [comment]
Feel free to reopen if needed
