### ISSUE TITLE
Query parameter cannot contain '#'

### ISSUE THREAD

**Issue by fielding34** [bguerout/jongo#260]
I am using Jongo 1.2. If I pass parameter containing "#", i will got IllegalArgumentException exception. 

```
collection.findOne("{mobile:#}", "12#12").as(User.class);

java.lang.IllegalArgumentException: Not enough parameters passed to query: { "mobile" : "12#12"}
```

**Comment by bguerout** [comment]
Hello,

I'm note able to reproduce the issue you describe.
According to this test, it should be ok https://github.com/bguerout/jongo/blob/678169f41289d3e89dd5b5f2034b9a130d5d38e3/src/test/java/org/jongo/marshall/ParameterQueryBindingTest.java#L174

Feel free to reopen this issue.
