### ISSUE TITLE
Problem with nested arrays

### ISSUE THREAD

**Issue by gabycperezdias** [bguerout/jongo#262]
Hi, I don't know if it's a real issue, but I couldn't find an answer, so... here I go.

I have a collection where each register look like this:
`{
"_id": ObjectId,
"associated" : [{
"_id": ObjectId,
...
}]
...
}`

When I update the register I do:
`DBSingleton.getJongo().getCollection("name").update(new ObjectId(obj.getId())).with(obj);`

This works everytime I need to put more items in "associated", and when I need to remove one or many items, but when "associated" has something in DB and I need to update it with an empty array, this doesn't work, the others changes are applied, but the array is not emptied.

And, yes, when this error occurs my obj.getAssociated() returns an empty array not null.

If this is not an issue, could you please help me with that? 

Thanks in advance,

**Comment by haraldrombaut** [comment]
Did you already try .with("#", obj)?

**Comment by gabycperezdias** [comment]
@haraldrombaut Yeah, if I do that, my empty field disappears from the register
