### ISSUE TITLE
jongo 1.2 incompatible with MongoDB Java Driver 3.0.3

### ISSUE THREAD

**Issue by julienlavergne** [bguerout/jongo#264]
Ok MongoClient getDB is deprecated and is always here.

But some complaints appears here and there:

https://groups.google.com/forum/#!topic/jongo-user/dlodf-PTlyQ

Can we support the two constructors with DB and the new MongoDatabase ?

maybe a PR ?

**Comment by haraldrombaut** [comment]
#254 already addresses this issue.
