### ISSUE TITLE
Generated Ids & Jongo migration: generated id is not set after an insert

### ISSUE THREAD

**Issue by yduponchel** [bguerout/jongo#269]
Hi,

in Jongo 1.0, when using an String id field with "@Id" annotation, the String representation of an objectid would be used as id. That was great.

With Jongo 1.2, I have 2 issues:
1. in some cases, the generated id is not set 
2. can't get any combination of "@MongoId" or "@MongoObjectId" to generate such a string represnetation of an object id without creating a nested $oid structure in mongo, which then creates issues when doing looking on with the _id parameter

more specifically, from the 6 examples listed here: http://jongo.org/#mapping, here is what I get following an insert

Friend1
* pojo.id => 0
* mongodb: "_id": 0

Friend2
* pojo.id => 0
* mongodb: "_id": 0

Friend3
* pojo.id => null
* mongodb: { "_id": { "$oid": "5612886bb388aeb4a8cb6961" } }

Friend4
* pojo.id => "5612886a6b7cc42640791746"
* mongodb: { "_id": { "$oid": "5612886a6b7cc42640791746" } }

Friend5
* pojo.id => "5612886a6b7cc42640791747"
* mongodb: { "_id": { "$oid": "5612886a6b7cc42640791747" } }

Friend6
* pojo.id => "5612886b6b7cc42640791748"
* mongodb: { "_id": { "$oid": "5612886b6b7cc42640791748" } }

and in particular, with jongo-1.0 and Friend3, I used to get 
Friend3 (jongo-1.0)
* pojo.id => "5612886bb388aeb4a8cb6961"
* mongodb: { "_id": "5612886bb388aeb4a8cb6961" }

Any clue what I am doing wrong, how to get back the generated id in all cases, and how to use the simpler string representation?

Cheers,

Yann.

**Comment by ctrimble** [comment]
@yduponchel you may want to take another look at this issue with the current master.  Several fixes for id fields just went in.

**Comment by bguerout** [comment]
Hello,

You can test the fixes @ctrimble are talking about in this early version.
**This version must be considered as a SNAPSHOT of future 1.3 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.3-early-20151113-0140</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by bguerout** [comment]
Please reopen if bug still occurs
