### ISSUE TITLE
Add logs

### ISSUE THREAD

**Issue by bguerout** [bguerout/jongo#27]
Few options:
- slf4j
- log4j
- java.util.logging
- LogListener (no logging API)

**Comment by SanderDN** [comment]
Is this something that's still on any roadmap?
This is quite urgent, since we have no way to log which queries are performed. Any attempts to show mongo java driver logging, only show technical info, and no actual queries.

Any way to currently show queries is much appreciated.

**Comment by candidtim** [comment]
For information, as of Mongo 3, its Java Driver supports logging with SLF4J, quite well configurable: http://mongodb.github.io/mongo-java-driver/3.2/driver/reference/management/logging/

**Comment by SanderDN** [comment]
Configuring the mongodb logging will provide us with some logging:

19:09:39.283 DEBUG org.mongodb.driver.protocol.query - Sending query of namespace myapp.collection on connection [connectionId{localValue:2, serverValue:9446}] to server myserver:27017
19:09:39.328 DEBUG org.mongodb.driver.protocol.query - Query completed

But this does not show us which query was actually performed (query text).

**Comment by peter-moore-surverysampling** [comment]
Bump!  As SanderDN mentions, the Mongo driver logging is entirely inadequate.  It shows that a query was run, but not the interesting details about that query.
