### ISSUE TITLE
Please update jongo.org

### ISSUE THREAD

**Issue by despirados** [bguerout/jongo#275]
Nice work, but please update your web site jongo.org. 
Please change: 
```
DB db = new MongoClient().getDB("dbname"); 
```
With: 
```
DB db = new DB(new MongoClient(),"dbname");
```

**Comment by androidmason** [comment]
It seems Jongo supports driver versions 2.13 and 3.0 that work both with MongoDB 3.0.
Just that for Mongo java driver 3.+  ~~getDB~~(String dbName) is deprecated.

And the code below : 

    DB db = new DB(new MongoClient(),"dbname");

will work only for Mongo java driver 3.+ not for the versions below.

**Comment by despirados** [comment]
Many thanks, got it !!

**Comment by bguerout** [comment]
Doc will be updated when issue https://github.com/bguerout/jongo/issues/254 will be done
