### ISSUE TITLE
Default cluster creation

### ISSUE THREAD

**Issue by ltanguy** [bguerout/jongo#276]
I have a strange behaviour since I added a reference to org.jongo in the build.gradle of my Spring Boot application.
I don't have any code referencing the jongo library (nor the mongo driver), but I see this line when I start my application:

> [main] INFO  o.m.d.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}

followed by an Exception:

> 17:14:47.946 [cluster-ClusterId{value='564df5765ca4813dd4b5f517', description='null'}-localhost:27017] INFO  o.m.d.cluster - Exception in monitor thread while connecting to server localhost:27017
> com.mongodb.MongoSocketOpenException: Exception opening socket

The mongo DB Driver is apparently trying to connect to a default cluster...

When I push the log level to DEBUG, I have multiple lines like the following one that appear:

> 17:15:21.009 [cluster-ClusterId{value='564df5765ca4813dd4b5f517', description='null'}-localhost:27017] DEBUG o.m.d.connection - Closing connection connectionId{localValue:4}

Is it an intended behaviour ?

**Comment by bguerout** [comment]
Hello,

Theses messages has not been logged by jongo but mongo java driver.

Can you post your modifications in build.gradle ?
