### ISSUE TITLE
NullPointerException when annotation is on Getter

### ISSUE THREAD

**Issue by arcadius** [bguerout/jongo#282]
Hello @bguerout 
We had a NPE when using the latest Jongo driver.

I am proposing a fix in pull request: https://github.com/bguerout/jongo/pull/280

Any suggestion or comment would be appreciated.

Thank you very much

**Comment by bguerout** [comment]
Pull request has been merged and will be released in v1.3. Thanks again

**Comment by arcadius** [comment]
Thank you very much @bguerout and @ctrimble for looking into this.

**Comment by bguerout** [comment]
1.3.0 has been released.
