### ISSUE TITLE
Would it be possible to get more frequent releases of this project?

### ISSUE THREAD

**Issue by ctrimble** [bguerout/jongo#285]
Would it be possible to get more frequent releases of this project?  The CloudBees early releases are good for short term testing, but it would be much easier on those downstream to have regular SNAPSHOTs and frequent point releases and patches.

**Comment by bguerout** [comment]
You are right.
I'm going to release 1.3 ASAP

**Comment by bguerout** [comment]
May be I have to have a look at https://github.com/bguerout/jongo/issues/284 before

**Comment by ctrimble** [comment]
Thanks @bguerout .

**Comment by bguerout** [comment]
Sounds good to me. I'm going to update website with contributions and then release

**Comment by ctrimble** [comment]
The conversation on #288 answers this question.  Thanks!

**Comment by bguerout** [comment]
1.3.0 has been released.
