### ISSUE TITLE
com.mongodb.DB will be deprecated

### ISSUE THREAD

**Issue by hbprotoss** [bguerout/jongo#289]
`com.mongodb.DB` in the constructor of Jongo will be deprecated

**Comment by jeanlaurent** [comment]
Would be cool to support the new `MongoDatabase` object since `DB` is going to be [deprecated](https://github.com/mongodb/mongo-java-driver/blob/8810c0a2e379fea40b6388c8a5aad31aa32aed82/driver/src/main/com/mongodb/Mongo.java#L439-L452)

**Comment by navkast** [comment]
+1

**Comment by navkast** [comment]
This is a duplicate of https://github.com/bguerout/jongo/issues/254

**Comment by bguerout** [comment]
@jeanlaurent You are right. 
Supporting the new MongoDatabase API implies a lot of work, you can follow news about this topic on issus #254

**Comment by bguerout** [comment]
I've just answered to this topic in issue #254
