### ISSUE TITLE
Optional<ObjectId> _id field in a class not recognized by JacksonObjectIdUpdater.isObjectId() at MongoCollection.save()

### ISSUE THREAD

**Issue by mancvso** [bguerout/jongo#291]
When modelling a POJO for interaction with Mongo trough Jongo i've used something like

``` java
class Pojo {
  public final Optional<ObjectId> _id;
  ...
}
```

But in Scala, using the jackson-scala-support with a modified Mapper on the constructor of Jongo

``` java
db = new DB(mongo,"panama_papers"); // 3.x
mapper = new JacksonMapper.Builder()
    .registerModule( new Jdk8Module() )
    .registerModule( new JavaTimeModule() )
    .registerModule( new ParameterNamesModule() )
    .registerModule( new DefaultScalaModule() )
    .build();
jongo = new Jongo(db, mapper);
```

``` scala
final case class Pojo(_id:Option[ObjectId] = None, ...
```

Querying, inserting, updating works great... But when using save on a modified object I've just retrieved from the DB, the object gets duplicated.

Changing the POJO signature from Optional<ObjectId> to ObjectId works, as expected.

Thing is, that semantically an ID is not existent when creating the object for inclusion on the DB, so a, Optional type is ideal to model the situation.

Is there any way to make [JacksonObjectIdUpdater](https://github.com/bguerout/jongo/blob/master/src/main/java/org/jongo/marshall/jackson/JacksonObjectIdUpdater.java#L97) recognize Scala's Option?

**Comment by bguerout** [comment]
Hello,

Can you post the structure of your object stored into MongoDB ?

**Comment by bguerout** [comment]
BTW you can test a POJO with a nullable ObjectId field with a getter which returns an Optional.
Not sure if this is ok in Scala.
See https://dzone.com/articles/java-8-optional-use-cases and http://blog.joda.org/2015/08/java-se-8-optional-pragmatic-approach.html

**Comment by mancvso** [comment]
The structure is in Scala (because it's easier and succinct to read for others) all storable (?) entities are using a common "trait" (interface in Java).

```scala
trait Entidad {
  val _id:java.util.Optional[ObjectId] = None // or val _id:Option[ObjectId]
  val _creado:LocalDateTime = LocalDateTime.now() // serialized as Json Array
  val _modificado:LocalDateTime = LocalDateTime.now() // serialized as Json Object
}

final case class Usuario (
    correo:String,
    clave:String,
    token:UUID = UUID.randomUUID(),
    maquinas:List[Maquina] = Nil // or List.empty
) extends Entidad
```

Will try your approach of the Optional returning getter.
