### ISSUE TITLE
Combine count and hint (or sort)

### ISSUE THREAD

**Issue by hlassiege** [bguerout/jongo#295]
Hi,

I'm currently using a count query which is very slow because Mongo choose the wrong index. 

I can solve it by adding a hint or if I add a sort (because with the sort, it force mongo to choose the only index that would satisfy this sort)

With the mongo shell, I can do it : 

db.something.find(...).hint(...).count()
db.something.find(...).sort(...).count()

Is it possible to perform a count query with a hint or a sort with Jongo ?

**Comment by hlassiege** [comment]
My question is not correct. Yes, I read the code and it's not possible.

The true question would be, is it possible to add this Feature ? :)

**Comment by bguerout** [comment]
You can use hint and sort methods  : 

```java
collection.find().hint("{$natural: 1}").sort("{name: 1}").as(Friend.class);
collection.find("{}").sort("{'address':1}").as(Friend.class);
```

**Comment by bguerout** [comment]
You can use sort and hint methods : 

```java
MongoCursor<Friend> friends = collection.find("{name:'John'}").hint("{$natural: 1}").sort("{name: 1}").as(Friend.class);
int nbResults = friends.count();
```

**Comment by bguerout** [comment]
Note that you can use raw DBObject : 

```java
MongoCursor<DBObject> rawResults = collection.find("{name:'John'}")
          .hint("{$natural: 1}")
          .sort("{name: 1}")
          .map(new RawResultHandler<DBObject>());
int nbResults = rawResults.count();
```

**Comment by hlassiege** [comment]
I should have seen that. Sorry and thanks for your answer :)
