### ISSUE TITLE
How to get Jongos MongoCollection with JongoNative

### ISSUE THREAD

**Issue by markhughes** [bguerout/jongo#310]
Using 1.4-early-20160606-0118.

Perhaps I've misunderstood but to use the latest MongoDB java driver we are supposed to use the new JongoNative.

But, it only returns the MongoCollection from MongoDB (`com.mongodb.client.MongoCollection`) unlike before (`org.jongo.MongoCollection`).

How do we go about getting `org.jongo.MongoCollection` from JongoNative? Or, are we required to use the MongoDB BSON filters now?

**Comment by bguerout** [comment]
This because `org.jongo.MongoCollection` can only be used with deprecated DB instance from mongo java driver. `JongoNative` returns `com.mongodb.client.MongoCollection`.

You can still use Jongo as follow :
```java
collection.findOne(jongo.query("{name : #}", "Abby"));
collection.insertOne(pojo);
...
```

You can find more examples here : https://github.com/bguerout/jongo/tree/master/src/test/java/org/jongo/use_native

Let me know what do you think about this new API.

**Comment by MarkehMe** [comment]
Ahh okay, I was basing it off the examples on the website. Oops, this works fine :)

**Comment by bguerout** [comment]
OK i'm really interested in your feedback about how it is easy to use JongoNative with `com.mongodb.client.MongoCollection` (jongo.query....)

**Comment by MarkehMe** [comment]
I'm about to have a go at putting it into a project, so i'll let you know how I go!

**Comment by MarkehMe** [comment]
Looks like it is just "find" not "findOne"

Like:
```java
User user = collection.find(query).first();
```

I simplified it a bit by creating a small helper method in my base class (everything here is very abstract haha) - makes it a bit tidier:

```java
	public Optional<T> get(String id) {
		T result = collection.find(q("{id : #}", id)).first();
		if (result == null) return Optional.empty();
		return Optional.of(result);
	}

	public Bson q(String query, Object... parameters) {
		return this.jongo().query(query, parameters);
	}

```
