### ISSUE TITLE
New version of jongo with mongo driver at least 3.4

### ISSUE THREAD

**Issue by karimad** [bguerout/jongo#316]
Hello,

When do you plan to release a version supporting at least the mongo driver 3.4 ?

Thanks

**Comment by bguerout** [comment]
Hello,

I can release an early version tomorrow.

About the 1.4, the new native API should be documented and probably better tested.

**Comment by karimad** [comment]
Thanks for your reply !

**Comment by bguerout** [comment]
Do you need an early release ?
Even if this is not an "official" release, this version can be used in an pom.xml.

**Comment by karimad** [comment]
We need a release version as we use it in my entreprise

**Comment by brainztorm** [comment]
+1 :) 
merci @bguerout !

**Comment by bguerout** [comment]
Here is a new beta version

``` xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>jongo-1.4-early-20171013-1609</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```
**Note that this version must be considered as a beta of the future 1.4.0 release**
