### ISSUE TITLE
Is this project still under development

### ISSUE THREAD

**Issue by RyanSusana** [bguerout/jongo#338]

**Comment by bguerout** [comment]
Yes this is still maintained but with a low commit rate. 
Nevertheless last month 1.3.1 and 1.4.0 were released.

The next released is the 1.5.0 with the new API (mongo-java-driver 3+)

See https://github.com/bguerout/jongo/milestones for more informations

**Comment by RyanSusana** [comment]
Thank the lord! I am using it with my new framework. Was wondering if you guys were gonna get past the deprecated getDb method.

Looking forward to helping out as much as I can!

Any ETA's on 1.5.0?

**Comment by hoegertn** [comment]
Anything new on 1.5?

**Comment by hoegertn** [comment]
Are there any plans to release 1.5 or is this project now no longer maintained?

**Comment by RyanSusana** [comment]
Same questions

**Comment by RyanSusana** [comment]
Is there any news on v1.5?

I depend on this update a little😁

**Comment by kehanDev** [comment]
Waiting for v1.5

**Comment by Ashwin-Surana** [comment]
We are planning to use Jongo in our new project. The deprecated method is a bit of a concern, we can live with it for a while but any updates on this will be really helpful :).

**Comment by RyanSusana** [comment]
I would go with the embedded mongo server instead @Ashwin-Surana
