### ISSUE TITLE
Unable to use 'arrayfilters' option in the update Query

### ISSUE THREAD

**Issue by Gnaneshwar511** [bguerout/jongo#339]
MongoDB has this feature to give the ability to update a/the part(s) of subarray. 

[MongoDB Manual](https://docs.mongodb.com/manual/reference/method/db.collection.update/index.html)

It is done with the use of 'arrayfilters' and I think it starts from Mongo3.6 version.

[My question on Stackoverflow for better understanding of the situation](https://stackoverflow.com/questions/50811991/use-arrayfilters-to-update-the-sub-array-using-jongo)

I can see that same feature doesn't work on using Jongo update method. Can we include it in future releases?

**Comment by bguerout** [comment]
Hello,

Can you please provide the full stacktrace ?

But i'm not sure you can achieve what you are trying to do with the current
version of Jongo.

**Comment by iotech-longtran** [comment]
hi @bguerout 

db.attributes_schema.update({'default.tables._objectId': '5cbf010e53fe' },
{$set:{"default.tables.$[i].schema_definition.$[j].visible": 1}},
{arrayFilters: [{"i._objectId": '5cbf010e53fe'},{"j._objectId": 'ac22d981e8e3'}]});

**Comment by iotech-longtran** [comment]
! com.mongodb.WriteConcernException: Write failed with error code 2 and error message 'No array filter found for identifier 'i' in path 'attributes.default.tables.$[i].schema_definition.$[j].visible''
