### ISSUE TITLE
Recording of Decimal128 via Jongo

### ISSUE THREAD

**Issue by LauraCouret** [bguerout/jongo#340]
I'm working with Jongo 1.4, which is supposed to take into account Decimal128 type. Thus, I would like to know why, when I'm trying to register a Decimal128 in a database, it appears like an Object and not like a NumberValue ?
Do you have any solution for me to force NumberValue ?
Thank you in advance for your answer.

**Comment by LauraCouret** [comment]
No answer ?

**Comment by bguerout** [comment]
Hello, can you provide a code snippet with the POJO your are trying to store ?

**Comment by LauraCouret** [comment]
I'm trying to store this POJO with a Decimal128 attribute :

![decimal128](https://user-images.githubusercontent.com/38243662/42205078-b39f7d32-7ea3-11e8-8bf8-d5a2a2c055a0.png)
But it appears like an Object in my database (with high, low, negative, nan, infinite and finite parameters) :

![capture du 2018-07-03 09-32-19](https://user-images.githubusercontent.com/38243662/42205222-1d6d05b8-7ea4-11e8-9261-8e7515e60d48.png)


However, what I would like is something like this :
![vf](https://user-images.githubusercontent.com/38243662/42205563-221b0168-7ea5-11e8-8e80-fd080ff49939.png)

That I created in this way :
![capture du 2018-07-03 09-37-51](https://user-images.githubusercontent.com/38243662/42205597-3d91a730-7ea5-11e8-84e6-ce31303ac426.png)

Do you have any proposition ?

**Comment by LauraCouret** [comment]
Do you need any other information ?

**Comment by bguerout** [comment]
Ok so i suppose you need to configure ObjectMapper to handle Decimal128.
I'm going to make a test

**Comment by LauraCouret** [comment]
Ok, thank's! Have you found anything yet ? What's the result ?

**Comment by LauraCouret** [comment]
Hello, 
I'm on this project only until July 20, do you think it will be ok ?

**Comment by LauraCouret** [comment]
Hello! Do you have some news ?

**Comment by bguerout** [comment]
This is not a working example but you need to create a custom serializer/deserializer:

```java
Mapper mapper = jacksonMapper()
.addSerializer(Decimal128.class, new JsonSerializer<Decimal128>() {
    @Override
    public void serialize(Decimal128 decimal, JsonGenerator jgen, SerializerProvider provider) throws IOException {
       //write value into the generator by using for example decimal.bigDecimalValue()
        jgen.writeNumber(...);
    }
})
.addDeserializer(Decimal128.class, new JsonDeserializer<Decimal128>() {
    @Override
    public Decimal128 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
        //read value from parser and create new instance of Decimal128
        return new Decimal128(...);
    }
})
.build();

Jongo jongo = new Jongo(getDatabase(), mapper);

...
```

**Comment by bguerout** [comment]
Note that Decimal128 should be support natively by jongo

**Comment by bguerout** [comment]
Here is a working example using BigDecimal (+de/serilization into string)

```java
 @Test
    public void canHandleDecimal128() {

        Decimal decimal = new Decimal();
        decimal.total = Decimal128.parse("10");

        collection.save(decimal);

        Decimal result = this.collection.findOne(decimal._id).as(Decimal.class);
        assertThat(result.total).isEqualTo(new Decimal128(10));
    }

    private static class Decimal {
        ObjectId _id;
        @JsonSerialize(using = Decimal128JsonSerializer.class)
        @JsonDeserialize(using = Decimal128JsonDeserializer.class)
        Decimal128 total;
    }

    private static class Decimal128JsonDeserializer extends JsonDeserializer<Decimal128> {
        @Override
        public Decimal128 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
            return new Decimal128(new BigDecimal(jp.getValueAsString()));
        }
    }

    private static class Decimal128JsonSerializer extends JsonSerializer<Decimal128> {

        @Override
        public void serialize(Decimal128 decimal, JsonGenerator jgen, SerializerProvider provider) throws IOException {
            jgen.writeString(decimal.bigDecimalValue().toString());
        }
    }
```

This test has been added into test suite: https://github.com/bguerout/jongo/blob/master/src/test/java/org/jongo/spike/QuestionsSpikeTest.java#L195

**Comment by LauraCouret** [comment]
The trouble with this is that writeNumber(BigDecimal value) transforms my value into a double value, not Decimal128 value...

**Comment by bguerout** [comment]
Have you checked with the second example ?

**Comment by LauraCouret** [comment]
"Note that Decimal128 should be support natively by jongo", not by jongo but by mongo, isn't it ?

**Comment by LauraCouret** [comment]
I saw your second example, but the trouble is that my Decimal128 values can't be registred like string in my database (I do statistics so I need numerical values)

**Comment by LauraCouret** [comment]
I also tried with this :
According to MongoDB documentation : 
![mongodoc](https://user-images.githubusercontent.com/38243662/43008132-84c9f2fe-8c3a-11e8-8d58-659a51c562f1.png)
(source : https://docs.mongodb.com/manual/reference/mongodb-extended-json/#numberdecimal)
However, Jongo does not recognize the property "$numberDecimal" so it doesn't work

**Comment by bguerout** [comment]
Not sure if the following serializer can do the job 

```java
    private static class Decimal128JsonSerializer extends JsonSerializer<Decimal128> {

        @Override
        public void serialize(Decimal128 decimal, JsonGenerator jsonGenerator, SerializerProvider provider) throws IOException {
            jsonGenerator.writeStartObject();
            jsonGenerator.writeFieldName("$numberDecimal");
            jsonGenerator.writeString(decimal.bigDecimalValue().toString());
            jsonGenerator.writeEndObject();
        }
    }
``

I'm going to try to add Decimal128 support into Jongo

**Comment by creativearmenia** [comment]
No plans to release version to support Decimal128 before 1.5.0?

**Comment by JulesCizor** [comment]
@bguerout : as @creativearmenia has said : "no plans to release version to support Decimal128 before 1.5.0?"

Is it possible to build by myself an intermediate version ?

**Comment by bguerout** [comment]
I think i can backport this fix an release a 1.4.1 version.

**Comment by JulesCizor** [comment]
This would be very appreciable :D 
An idea of the release date ?

**Comment by bguerout** [comment]
I've deployed a SNAPSHOT version.
It should be great if you can validate that this version solved the issue.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
...
    <dependencies>
        <dependency>
            <groupId>org.jongo</groupId>
            <artifactId>jongo</artifactId>
            <version>1.4.1-SNAPSHOT</version>
        </dependency>
    </dependencies>


    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <name>Sonatype Public</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
...
</project>
```

**Comment by JulesCizor** [comment]
After testing in an environnement composed of :
- Play Framework 1.5.1
- Mongo 3.4.24

It works perfectly !

Conf add in play depencies 👍 
`require:
    - play
    - ...
    - org.jongo -> jongo 1.4.1-SNAPSHOT
    - ...

repositories:
    - sonatype:
        type: iBiblio
        root: "https://oss.sonatype.org/service/local/repositories/snapshots/content/"
        contains:
            - org.jongo -> *` 

Result obtained and observed using Robo3T :

![test_result_in_mongo](https://user-images.githubusercontent.com/17086231/76611106-433f5300-651a-11ea-8cf3-c2efa9f68564.png)

**Comment by JulesCizor** [comment]
Please let me know when version 1.4.1 will be officially delivered.
Thank you in advance

**Comment by bguerout** [comment]
1.4.1 has just been released

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
...
    <dependencies>
        <dependency>
            <groupId>org.jongo</groupId>
            <artifactId>jongo</artifactId>
            <version>1.4.1</version>
        </dependency>
    </dependencies>
...
</project>
```

**Comment by JulesCizor** [comment]
Thank you for everything
