### ISSUE TITLE
Add TravisCI build status on readme

### ISSUE THREAD

**Issue by albertotn** [bguerout/jongo#344]
Hi! Thanks for your project! I've seen you have put jongo also on TravisCI and because there is a lot of "green status" on build history (see https://travis-ci.org/bguerout/jongo/builds ), why you don't add on readme  I mean this small image: https://api.travis-ci.org/bguerout/jongo.svg?branch=master 

Keep going with this good project!

**Comment by bguerout** [comment]
Thanks
