### ISSUE TITLE
[security] Upgrade Jackson Databind to 2.9.7 or higher

### ISSUE THREAD

**Issue by sumerjabri** [bguerout/jongo#349]
Jackson Databind version 2.9.5 has a security vulnerability, see here: https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72451

Please upgrade `com.fasterxml.jackson.core:jackson-databind` to version 2.9.7 or higher.

**Comment by bguerout** [comment]
Hello

Thanks for your PR.
Can you pick your commit to apply it against the branch `releases/1.4.x` ?
So the fix can be released has an hotfix.
