### ISSUE TITLE
Aggregation compatibility

### ISSUE THREAD

**Issue by yoav-lavi** [bguerout/jongo#356]
I've been using aggregation with version `3.6.1` of the MongoDB Driver and it seems to work fine, although the docs say it's only compatible with 2.2. Could you clarify this?
Also, I've not been able to reverence `JongoNative` on version 1.4.0. When will this be included?
Thanks.

**Comment by bguerout** [comment]
Hello,

1.4.1 has just been released.
It  has been tested with the following mongodb-java-driver versions : [3.8.0, 3.12.2]

Note that `JongoNative` is not included into this release.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
...
    <dependencies>
        <dependency>
            <groupId>org.jongo</groupId>
            <artifactId>jongo</artifactId>
            <version>1.4.1</version>
        </dependency>
    </dependencies>
...
</project>
```
