### ISSUE TITLE
Compatibility with latest mongo-java-driver

### ISSUE THREAD

**Issue by AnthonyDJCorrado** [bguerout/jongo#357]
Hello,

Based on the pom.xml, we can see that jongo is relying on mongo-java-driver 3.5 which is, as per mongodb doc, not compatible with MongoDB 3.6+ version. 

![image](https://user-images.githubusercontent.com/19515923/53507212-c16bbb80-3ab7-11e9-82db-00d5e25d9c75.png)

Is there a plan to make jongo compatible with the latest versions of the mongo-java-driver so we can use it with MongoDB 4.0+?

Have you identified what is blocking to use the latest mongo-java-driver version? Do you need help to solve them?

Thank you in advance for your reply.

Regards,
Tony

**Comment by RyanSusana** [comment]
Hi I also would like to know this, thanks.

**Comment by bguerout** [comment]
Hello, 

Jongo 1.4.0 is compatible with mongodb-java-driver 3.8+ and with MongoDB v4+.

I've created a pull request to force tests to be run against mongodb-java-driver 3.10 and MongoDB v4+ https://github.com/bguerout/jongo/pull/363/files

**Comment by bguerout** [comment]
Jongo is compatible with:

- mongo-java-driver 3.3.0+
- MongoDB 2.6.11+
- jackson 2.7.0+

You can find all the versions tested here : https://github.com/bguerout/jongo/pull/365/files#diff-e7430fb515dbcaca3fe82f60c0f3e987R26

**Comment by bguerout** [comment]
Feel free to reopen if needed
