### ISSUE TITLE
Any News?

### ISSUE THREAD

**Issue by RyanSusana** [bguerout/jongo#362]
Hi @bguerout and the rest of the team.

Any status update on Mongo 4+ support?

**Comment by RyanSusana** [comment]
??

**Comment by bguerout** [comment]
Hello,

I haven't tested yet.

I'm going to check if all integration tests pass with MongoDB v4+

**Comment by bguerout** [comment]
You can find more informations here : https://github.com/bguerout/jongo/issues/357

**Comment by bguerout** [comment]
I closed this issue in favor of https://github.com/bguerout/jongo/issues/357
