### ISSUE TITLE
generating and setting the id value of an annotated field should be moved to  the ObjectIdUpdater

### ISSUE THREAD

**Issue by bertramn** [bguerout/jongo#373]
I am trying to make persistence Id annotation work by storing the pojo `_id` field as `string` in mongo instead of `oid`. I had some discussions with mongodb engineers which confirmed that there is not much difference in terms of space and performance between storing/using either data type.

Unfortunately I ran into difficulties writing the right data type to mongo as everything seems to be hardwired in Jongo to force storing the object id as `oid`. Specifically I found that [JacksonObjectIdUpdater#setObjectId](https://github.com/bguerout/jongo/blob/2114030d01b707415802129062de71c60a4557ac/src/main/java/org/jongo/marshall/jackson/JacksonObjectIdUpdater.java#L78) should probably be in charge of generating the object id value and updating the pojo. The generation of a default object id is currently done in [Insert](https://github.com/bguerout/jongo/blob/master/src/main/java/org/jongo/Insert.java#L74) and [JongoCodec](https://github.com/bguerout/jongo/blob/master/src/main/java/org/jongo/JongoCodec.java#L65). This would bring some of the scattered functionality back together in the ObjectIdUpdater where it is easier to manage the different permutations on how a field is detected and defaulted.

**Comment by bguerout** [comment]
Hello,

You can have a look at
https://github.com/bguerout/jongo-extras/tree/master/javax-persistence
It allows POJO to be annotated with Persistence annotations as follow :
https://github.com/bguerout/jongo-extras/blob/master/javax-persistence/src/main/java/org/jongo/persistence/PersistenceFriend.java#L19

Is it what you are looking for?

**Comment by bertramn** [comment]
I did use that configuration as a basis but found quite a few issues with it. Ended up rewriting a bunch of classes and short circuiting the `IdUpdate. mustGenerateObjectId()` and `IdUpdate.setObjectId()` methods to default the pojo variable to `String` OR `ObjectId` based on what the type declaration of the field was. I will make a public example of this code as it is easier to show in unit tests the different types of scenarios I tried to cover.

**Comment by bertramn** [comment]
On that note, I also had a bit of a look into the "newer" 3.7+ features of the mongo driver and what you tried to do with JongoNative. It looks possible to bridge Jackson directly to the mongo bson components without the need for undercouch. I have a need to use Jackson as the OR mapper as we have a lot of custom modules for Jackson that we would have to "recreate" for mongo driver just to store our models in mongo and put them on the HTTP wire using Jackson.
