### ISSUE TITLE
Add support for optimistic locking

### ISSUE THREAD

**Issue by btiernay** [bguerout/jongo#96]
A missing feature that Jongo does not support, but other MongoDB projects such as Morphia do support, is transparent optimistic locking. This is typically done via an annotation such as @Version (see http://code.google.com/p/morphia/wiki/AllAnnotations#Version).

> Marks a field in an @Entity to control optimistic locking for that entity. If the versions 
> change while modifying an entity a ConcurrentModificationException will be throw in the
> write method (save/delete/etc). This field will be automatically managed for you -- there is
> no need to set a value and you should not do so anyway.

**Comment by haraldrombaut** [comment]
+1

**Comment by yaozhanwei** [comment]
+1

**Comment by Serializator** [comment]
+1

**Comment by flavia-it** [comment]
+1

**Comment by tadovas** [comment]
+1

**Comment by Serializator** [comment]
+1
